FROM quay.io/drsylent/cubix/block2/optional-base:ubuntu23   

FROM eclipse-temurin:17-jre
RUN mkdir /opt/app && chown 1001 -R /opt/app

USER 1001
WORKDIR /opt/app

COPY --chown=1001 target/*.jar app.jar
CMD ["java", "-jar", "app.jar"]
