# Building stage
FROM openjdk:17-jdk-slim AS builder

USER root
RUN mkdir /opt/build
WORKDIR /opt/build

COPY .mvn .mvn
COPY src src
COPY mvnw .
COPY pom.xml .

RUN --mount=type=cache,target=/root/.m2 ./mvnw clean verify && rm -rf /var/lib/apt/lists/*

# Packaging stage
FROM quay.io/drsylent/cubix/block2/optional-base:ubuntu23

ARG IMAGE_BUILDER
LABEL image.builder="${IMAGE_BUILDER}"

USER root
RUN mkdir /opt/app && chown root -R /opt/app && apt -y update && apt -y install openjdk-17-jre && rm -rf /var/lib/apt/lists/* && apt -y autoremove

EXPOSE 8080

WORKDIR /opt/app
COPY --chown=root --from=builder /opt/build/target/*.jar app.jar

ENTRYPOINT exec java $JAVA_OPTS -jar app.jar $JAR_ARGS
