FROM quay.io/drsylent/cubix/block2/optional-base:ubuntu23

ARG IMAGE_BUILDER
LABEL image.builder="${IMAGE_BUILDER}"

USER root
RUN mkdir /opt/app && chown root -R /opt/app && apt -y update && apt -y install openjdk-17-jre && apt -y autoremove && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app

COPY --chown=root target/*.jar app.jar
ENTRYPOINT exec java $JAVA_OPTS -jar app.jar $JAR_ARGS
