version: "3.7"

services:

  backend-opt-app:
    image: quay.io/drsylent/cubix/block2/optional-backend:springboot3
    ports:
      - "8082:8080"
    environment:
      - name=value

  frontend-opt-app:
    image: frontendsb3:v1.0.0
    depends_on:
      - backend-opt-app
    ports:
      - 8081:8080
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - JAR_ARGS=${JAR_ARGS}
      - BACKEND_URL=${BACKEND_URL}
      - SPRING_CONFIG_LOCATION=${SPRING_CONFIG_LOCATION}
